### ISSUE TITLE
CRUD posts

### ISSUE THREAD

**Issue by cavmandos** [cavmandos/P5#10]

**Comment by cavmandos** [comment]
- [x] Display posts -> reverse (home, admin, posts pages)

**Comment by cavmandos** [comment]
- [x] Click and display the right post (READ)

**Comment by cavmandos** [comment]
- [x] Create a post with the form

**Comment by cavmandos** [comment]
- [x] Update a post
- [x] Delete a post

**Comment by tecuzin** [comment]
Fix the redirection after posting the post data
